27

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -66,15 +66,6 @@ jobs:
         run: echo "::set-output name=branch_type::$(if [[ $GITHUB_REF =~ ^refs/heads/release/.*$ ]]; then echo 'release'; else echo 'other'; fi)"
         shell: bash
 
-      # - name: Build and package app for macOS
-      #   if: matrix.os == 'macos-latest' && steps.determine-branch.outputs.branch_type == 'release'
-      #   run: |
-      #     flutter build macos --release
-      #     mkdir -p release
-      #     hdiutil create -volname "${{ env.APP_NAME }}" \
-      #                    -srcfolder "build/macos/Build/Products/Release/${{ env.APP_NAME }}.app" \
-      #                    -ov -format UDZO "release/release-${{ env.APP_NAME }}-${{ env.APP_VERSION }}.dmg"
-      #   shell: bash
       - name: Build and package app for macOS
         if: matrix.os == 'macos-latest'
         run: |
@@ -115,7 +106,7 @@ jobs:
 
       - name: Create GitHub Release
         id: create_release
-        if: matrix.os == 'macos-latest'
+        if: matrix.os == 'macos-latest' || matrix.os == 'windows-latest'
         uses: actions/create-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
@@ -155,6 +146,14 @@ jobs:
       - name: Print working directory
         run: pwd
 
+      - name: Check Windows build exists
+        if: matrix.os == 'windows-latest'
+        run: |
+          if [ ! -f "release/release-${{ needs.build.outputs.APP_NAME }}-${{ needs.build.outputs.APP_VERSION }}.exe" ]; then
+            echo "Windows build file not found!"
+            exit 1
+          fi
+
       - name: Upload Windows build to GitHub Release
         if: matrix.os == 'windows-latest'
         uses: actions/upload-release-asset@v1
@@ -162,9 +161,17 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
         with:
           upload_url: ${{ needs.build.outputs.upload_url }}
-          asset_path: /release/release-${{ needs.build.outputs.APP_NAME }}-${{ needs.build.outputs.APP_VERSION }}.exe
+          asset_path: release/release-${{ needs.build.outputs.APP_NAME }}-${{ needs.build.outputs.APP_VERSION }}.exe
           asset_name: release-${{ needs.build.outputs.APP_NAME }}-${{ needs.build.outputs.APP_VERSION }}.exe
           asset_content_type: application/octet-stream
+
+      - name: Check macOS build exists
+        if: matrix.os == 'macos-latest'
+        run: |
+          if [ ! -f "release/release-${{ needs.build.outputs.APP_NAME }}-${{ needs.build.outputs.APP_VERSION }}.dmg" ]; then
+            echo "macOS build file not found!"
+            exit 1
+          fi
 
       - name: Upload macOS build to GitHub Release
         if: matrix.os == 'macos-latest'
@@ -173,6 +180,6 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
         with:
           upload_url: ${{ needs.build.outputs.upload_url }}
-          asset_path: /release/release-${{ needs.build.outputs.APP_NAME }}-${{ needs.build.outputs.APP_VERSION }}.dmg
+          asset_path: release/release-${{ needs.build.outputs.APP_NAME }}-${{ needs.build.outputs.APP_VERSION }}.dmg
           asset_name: release-${{ needs.build.outputs.APP_NAME }}-${{ needs.build.outputs.APP_VERSION }}.dmg
           asset_content_type: application/x-apple-diskimage
